[discord]
investigation_team_guild_id = 1234  ## set this to the main server, it will check if they have the role in this guild
investigation_team_role_id = 1234   ## set this to what roleid is required to create cases
bot_name = "API"   ## what the bot refers to itself as (if speaking in 1st person for some reason)

[api]
master_password = "master_password_for_the_api"   ## let's the API distinguish between a random person and the discord bot
mongodb_db_name = "database"
proof_proxy = true   ##  do you want to upload all discord proofs to an external site? (edit .env) 

url = "https://127.0.0.1:6565"        ## it MUST include the slash at the end AND include the protocol at the beginning (https://)
port = 6565     ##  same port used in the url

[general]
debug_mode = true
